name: Trigger auto deployment for ai-investment-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ai-investment-app-AutoDeployTrigger-d825f79c-ef2c-4955-a563-2f31f325643c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AIINVESTMENTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AIINVESTMENTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AIINVESTMENTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          acrName: aiinvestmentregistry
          containerAppName: ai-investment-app
          resourceGroup: InvestmentResearchRG
          imageToBuild: aiinvestmentregistry.azurecr.io/ai-investment-app:${{ github.sha }}


